[package]
name = "awsudo"
version = "0.1.0"
authors = ["Marcelo Boeira <me@marceloboeira.com>"]

[profile.release]
panic = "abort"

[dependencies]
clap = "2.31.2"
rusoto_core = "0.33"
rusoto_sts = "0.33"
rust-ini = "0.12"
chrono = "0.4"
dirs = "1.0.5"
